# Base du language

## les types

Assignement de la valeur 1 à la variable a.

Cette variable est "typée" ici c'est un entier = integer = int


In [1]:
a = 1
print(a)
print(type(a))

1
<class 'int'>


In [8]:
a = 1
type(a)

int

Il y a différents types en python

In [ ]:
b = 2.456
print(b)
print(type(b))

2.456
<class 'float'>


On peut effectuer des opérations sur ces variables.
Notez le changement de type.

In [ ]:
c = a+b
print(c)
print(type(c))

3.456
<class 'float'>


Gestion des chaines de carractères

In [ ]:
s = 'hello'
print(s)
print(type(s))


hello
<class 'str'>


In [ ]:
s2 =   "hel'lo"  
print(s2)

hel'lo


In [ ]:
s3 = """youpi

éè $ ê


sdfsdfsdf
"""
print(s3)


youpi

éè $ ê


sdfsdfsdf



Opération sur str : concaténation

In [ ]:
s4 = s3+s2+s3
print(s4)


youpi

éè $ ê


sdfsdfsdf
hel'loyoupi

éè $ ê


sdfsdfsdf



Chaque variable est un object qui a des méthodes:

In [ ]:
#s4.upper?
s4.upper()

"YOUPI\n\nÉÈ $ Ê\n\n\nSDFSDFSDF\nHEL'LOYOUPI\n\nÉÈ $ Ê\n\n\nSDFSDFSDF\n"

Formatage des str

In [10]:
print(type(c))
#s5 = 'ma variable est '+ c +' !'
s5 = 'ma variable est '+ str(c) +' !'
s5


<class 'float'>


'ma variable est 3.456 !'

In [11]:
s6 = '3.56'
print(s6, type(s6))
f6 = float(s6)
print(f6, type(f6))

3.56 <class 'str'>
3.56 <class 'float'>


In [12]:
s5 = f'ma variable est {c} !'
s5

'ma variable est 3.456 !'

In [13]:
s5 = 'ma variable est {}'.format(c)
s5

'ma variable est 3.456'

Autre type utile : bool et complex

In [14]:
flag1 = True
flag2 = False
flag3 = flag1 and flag2
print(flag3, type(flag1))


False <class 'bool'>


In [15]:
cc = 50 + 50j
print(cc, type(cc))

(50+50j) <class 'complex'>


## Création d'une fonction

On peut créer des fonctions avec des variables en entrée et une variable de sortie.

Attention à l'indentation, cela definit le **block**.

En python c'est 4 espaces.



In [9]:
def mon_add(a, b):
    j = a+b
    s = f'Résultat: {a} + {b} = {j}'
    return s    

res = mon_add(5, 4)
print(res)
#print(j)

Résultat: 5 + 4 = 9


In [10]:
aa = 3
bb = 77
res = mon_add(aa, bb)
print(res)


Résultat: 3 + 77 = 80


Il peut y avoir plusieurs variables de sortie.

In [14]:
def mon_add_bis(a, b):
    c = a+b
    s = f'Résultat: {a} + {b} = {c}'
    return s, c

res, res2 = mon_add_bis(5, 4)
print(res)
print(res2)


Résultat: 5 + 4 = 9
9


Python permet d'avoir des variables facultatives.

In [15]:
def mon_add_ter(a, b, c=1, d=3):
    t = a+b+c+d
    s = f'Résultat: {a} + {b} + {c} + {d} = {t}'
    return s

res = mon_add_ter(aa, bb)
print(res)
res = mon_add_ter(aa, bb, c = 6, d = 9)
print(res)
res = mon_add_ter(aa, bb, d = 9)
print(res)


Résultat: 3 + 77 + 1 + 3 = 84
Résultat: 3 + 77 + 6 + 9 = 95
Résultat: 3 + 77 + 1 + 9 = 90


Voir uniquement des varibales facultatives.

In [16]:
def mon_add_4(c = 1, d = 3):
    t = c+d
    s = f'Résultat: {c} + {d} = {t}'
    return s

res = mon_add_4() # ici y'a rien
print(res)


Résultat: 1 + 3 = 4


## Quelques opérateurs courants:
 * addition soustraction
 * multiplication, division, division entière
 * puissance
 * opérateur boolean
 
(Attention en python 2.X et 3.X la division n'est pas la même - c'est mieux en python 3.X)

In [17]:
a, b, c = 2, 10, 20
r = a + b * c
print(r)


202


In [18]:
a, b = 3, 10
r = b / a
print(r)
r = b // a # division entière
print(r)
print(b % a)

3.3333333333333335
3
1


In [19]:
a = 27.
r = a ** 2
print(r)
r = a ** (1/3)
print(r)

729.0
3.0


# attention opérateur booléan amélioré
and or not

In [20]:
a = True
b = True
res = not(a or b)
print(res)
type(a)

False


bool

# attention opérateur booléan classique = élément par élément = bit a bit
& | ~

In [21]:
# attention opérateur booléan classique = agit bit a bit
a = 0b101111
b = 0b110010

res = (a & b)
print(bin(res))
res2 = (a | b)
print(bin(res2))



0b100010
0b111111


# Block conditionnel

In [22]:
pval = .00065424
seuil = 0.001

if pval < seuil:
    print('je suis hyper content')
elif pval == seuil:
    print("personne n'en saura rien")
else:
    print("qui m'a piqué mon cyanure")


je suis hyper content


## les collections

### list

suite d'éléments **hétérogènes**.

accessible par index entier, l'opérateur + est une concaténation

In [23]:
l = [12, 34., 4, 'lkjlkj' ]
print(l)
print(type(l))


[12, 34.0, 4, 'lkjlkj']
<class 'list'>


In [25]:
l2 = [12, 34.]  
l3 = l+l2
print(l3)


[12, 34.0, 4, 'lkjlkj', 12, 34.0]


On peut accéder et écrire dans une liste avec son index (zero based)

In [26]:
a = l[1]
print(a)
a = l[3]
print(a)
l[2] = 40
print(l)


34.0
lkjlkj
[12, 34.0, 40, 'lkjlkj']


Différentes syntaxes

In [29]:
l = list()
print(type(l))
l = []
print(type(l))

<class 'list'>
<class 'list'>


Ajout d'un élément  à une liste

In [30]:
l = []
l.append(10.)
l.append('yep')
print(l)

[10.0, 'yep']


In [31]:
l3 = l+l+l+l
#l3 = l*4
print(l3)


[10.0, 'yep', 10.0, 'yep', 10.0, 'yep', 10.0, 'yep']


### dict
Collection d'éléments hétérogènes accesibles par un label, appelé 'clef' (keys).





In [32]:
d = dict()
d = { }
d = {'a' : 1.,
     'b' : 60, 
     'c' : 'lkjlkj'  }


In [34]:
print(d['a'])
print(d['c'])


1.0
lkjlkj


In [35]:
d['c'] = 50
print(d['c'])
print(d)

50
{'a': 1.0, 'b': 60, 'c': 50}


 On peut ajouter une nouvelle paire clef/valeur

In [36]:
d['x'] = 'youpi'

In [37]:
print(d.keys())

dict_keys(['a', 'b', 'c', 'x'])


In [38]:
print(d.values())

dict_values([1.0, 60, 50, 'youpi'])


## les boucles et iterateurs

### Boucle for avec range (par compteur)

In [42]:
for i in range(10):
    print('ma variable i vaut', i)

ma variable i vaut 0
ma variable i vaut 1
ma variable i vaut 2
ma variable i vaut 3
ma variable i vaut 4
ma variable i vaut 5
ma variable i vaut 6
ma variable i vaut 7
ma variable i vaut 8
ma variable i vaut 9


### Boucle avec elements

In [43]:
liste_de_lettres = ['a','b','c','d','e','f','g','h']

for lettre in liste_de_lettres:
    print(lettre)

a
b
c
d
e
f
g
h


### Enumerate

In [44]:
for i,elem in enumerate(liste_de_lettres):
    print(i, ':', elem)

0 : a
1 : b
2 : c
3 : d
4 : e
5 : f
6 : g
7 : h


### Boucle sur dictionnaire

In [45]:
dict_alphabet = {'a':10,'b':20.0,'c':"hello"}

In [46]:
for key in dict_alphabet.keys():
    print(key)

a
b
c


In [47]:
for val in dict_alphabet.values():
    print(val)
    

10
20.0
hello


In [48]:
for key in dict_alphabet.keys():
    print(key, dict_alphabet[key])
    

a 10
b 20.0
c hello


### Compréhension de liste

In [60]:
carres = [ i**2 for i in range(5)]
print(carres)

[0, 1, 4, 9, 16]


In [62]:
cubes = { str(i): i**3 for i in range(5)}
print(cubes)

{'0': 0, '1': 1, '2': 8, '3': 27, '4': 64}


### Range avec plusieurs arguments

L'aide de range propose plusieurs signatures :

- La signature avec un seul argument que nous avons utilisée jusqu'ici : `range(stop)`.
- Une signature avec 2 arguments : `range(start, stop)`
- Une signature avec 3 arguments : `range(start, stop, step)`

In [52]:
range?

Init signature: range(self, /, *args, **kwargs)
Docstring:     
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).
Type:           type
Subclasses:     

In [53]:
for i in range(5,10):
    print(i)

5
6
7
8
9


In [54]:
for i in range(5,20,2):
    print(i)


5
7
9
11
13
15
17
19


In [55]:
for i in range(20,2,-1):
    print(i)

20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3


### Indexation des éléments

On peut acceder à des elements par leur index, entre 0 et N-1 si on a N elements dans une liste

In [56]:
liste_de_lettres = ['a','b','c','d','e','f','g','h']

print(liste_de_lettres[0])

a


In [57]:
print(liste_de_lettres[1])

b


In [58]:
print(liste_de_lettres[-1])

h


In [59]:
# et on peut faire du moonwalk...
print(liste_de_lettres[-2])

g


# utiliser une bobliotheque externe

In [39]:
# cas 1
import numpy
numpy.zeros(5)


array([0., 0., 0., 0., 0.])

In [40]:
# cas 2
import numpy as np
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [41]:
# cas 3
from numpy import zeros, ones
zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
# cas 4
from numpy import *
zeros(5)

array([0., 0., 0., 0., 0.])

On peut utiliser un sous-module

In [43]:
import scipy.signal
scipy.signal.filtfilt

<function scipy.signal._signaltools.filtfilt(b, a, x, axis=-1, padtype='odd', padlen=None, method='pad', irlen=None)>

On peut utiliser une bibliotheque local (maison) avec une fichier dans le meme folder

In [1]:
import ma_bibliotheque
ma_bibliotheque.affiche_un_beau_triangle(n=5)

ma_bibliotheque.affiche_un_beau_triangle_tete_en_bas(n=10)

|\
| \
|  \
|   \
|    \
------
____________
|          /
|         /
|        /
|       /
|      /
|     /
|    /
|   /
|  /
| /
