
# Manipulation de fichiers


# open

Le mode est donné sous la forme d'une chaîne de caractères. Voici les principaux modes :

    'r' : ouverture en lecture (Read).

    'w' : ouverture en écriture (Write). Le contenu du fichier est écrasé. Si le fichier n'existe pas, il est créé.

    'a' : ouverture en écriture en mode ajout (Append). On écrit à la fin du fichier sans écraser l'ancien contenu du fichier. Si le fichier n'existe pas, il est créé.
    

In [1]:
f = open("toto.txt",mode='w')
f.write('yep')

3

# close

Lorsque l'on a fini de manipuler un fichier ouvert, il est normalement necessaire de le fermer, pour liberer les ressources liées à ce fichier

In [3]:
f.close()

# with

La "vraie" maniere "pythonique" de faire consiste a utiliser le mot-clé "with". Ceci evite d'avoir à fermer explicitement le fichier avec close. C'est un gestionnaire de contexte, il encapsule une série d'opération et gère les exceptions.

In [4]:
with open("toto.txt",'r') as f:  # le fichier existe à l'avance sinon error
    print(f.closed) ## closed (et pas 'close') est un marqueur booleen indiquant si le fichier est ouvert ou fermé
print(f.closed)


False
True


# read

Tout le contenu du fichier est lu d'un coup

In [5]:
### je veux voir le contenu de mon fichier
with open("toto.txt",'r') as f:
    val = f.read() 
print('val : ', val)

val :  yep


# readlines

Le contenu du fichier est lu ligne par ligne

In [6]:
# let's write a multi line
txt = """yep
yop
yip
"""
with open("toto2.txt",'w') as f:
    f.write(txt)

In [7]:
### je veux voir le contenu de mon fichier ligne par ligne
f = open("toto2.txt",'r')
lines = f.readlines()
f.close()
print(lines)

['yep\n', 'yop\n', 'yip\n']


In [8]:
### je veux voir le contenu de mon fichier ligne par ligne
with open("toto2.txt",'r') as f:
    lines = f.readlines()
print(lines)

['yep\n', 'yop\n', 'yip\n']


# ENCODAGE


# Concept

**Encodage** : \
Transformer (convertir) des données (ex: texte, image, son) \
en un format standardisé (ex : binaire, hexadécimal, etc.) \
pour faciliter le stockage, la transmission ou le traitement par des systèmes informatiques.

Exemples : \
Texte : UTF-8 (caractères → bytes). \
Image : PNG/JPEG (pixels → compression binaire). \
Son : MP3 (ondes → compression numérique).




**Encoder, par exemple les charactères alphabétiques**
1. **Bit** (Binary Digit) \
    • Définition : Unité de base de l’informatique. \
    • Valeur : 0 ou 1 (état électrique : éteint/allumé). \
    • Exemple : 1 ou 0. 

2. **Octet** (**Byte**) \
    • Définition : Groupe de 8 bits. \
    • Valeur : Représente 256 valeurs possibles (de 00000000 à 11111111 en binaire, soit 0 à 255 en décimal). \
    • Exemple :  \
             ◦ 01100001 = 97 (décimal) = 'a' (caractère ASCII). \
             ◦ 1 octet = 1 byte (les deux termes sont synonymes en pratique). 

3. **Texte** \
    • Définition : Suite de caractères (lettres, chiffres, symboles) encodés pour être stockés ou transmis. \
    • Exemple : "Bonjour" est un texte composé de 7 caractères. 

4. **ASCII** (American Standard Code for Information Interchange)\
    • Définition : Table de correspondance entre nombres (bytes) et caractères. \
    • Portée : \
        ◦ 7 bits (128 caractères) : lettres latines, chiffres, symboles de ponctuation. \
        ◦ Exemples : \
            ▪ 65 = 'A', 97 = 'a', 48 = '0'. \
        ◦ Limite : Ne couvre pas les caractères accentués (é, è, ç) ou les alphabets non latins (chinois, arabe, etc.). \

5. **UTF-8** (Unicode Transformation Format - 8 bits) \
    • Définition : Encodage **variable** (extension d’ASCII, sur 1 ou plusieurs bytes) pour représenter tous les caractères Unicode. \
    • Fonctionnement : \
        ◦ 1 byte pour les caractères ASCII (compatibilité). \
        ◦ 2 à 4 bytes pour les autres (ex. : é = 0xC3 0xA9, emoji = 4 bytes). \
    • Avantages : \
        ◦ Supporte toutes les langues (chinois, arabe, émojis, etc.). \
        ◦ Rétrocompatible avec ASCII. \
    • Exemple : \
        ◦ "café" en UTF-8 : 0x63 0x61 0x66 0xC3 0xA9 le é occupe 2 bytes. (donné en héxadécimal pour unr représentation compacte. En binaire ça donnerait 01100011 01100001 01100110 11000011 10101001)


# Lecture string/bytes et importance de l'encoding (UTF-8)

str = Pour le texte humain (multi-langue, symboles).

bytes = Pour les données binaires (réseau, fichiers, chiffrement).

In [9]:
chaine1 = b"Ceci est une chaine d'octets"

print(chaine1)
print(type(chaine1))
print(chaine1[-1])

#s (minuscule): 
#  Code décimal : 115
#  Code hexadécimal : 0x73
#  Représentation binaire : 01110011


chaine2 = "Ceci est une chaine de caractères particuliers 你好 صباح الخير"

print(chaine2)
print(type(chaine2))
print(chaine2[-2])


b"Ceci est une chaine d'octets"
<class 'bytes'>
115
Ceci est une chaine de caractères particuliers 你好 صباح الخير
<class 'str'>
ي


### UTF-8

- ASCII (7 bits) encode 128 caractères basiques (anglais), de façon unique.
- Unicode étend cela à tous les alphabets (🌍, é, 字).
- UTF-8 est un encodage d’Unicode rétro-compatible avec ASCII (1 byte pour ASCII, 2-4 bytes pour les autres).

In [10]:
# lets put this 2 object in the same file
with open("chaine.txt",'wb') as f:
    f.write(chaine1)

with open("chaine.txt",'a') as f:
    f.write('\n')
    f.write(chaine2)

In [11]:
with open('chaine.txt', mode= 'r', encoding='utf8') as f:
    txt = f.read()
print(txt, type(txt), len(txt))

Ceci est une chaine d'octets
Ceci est une chaine de caractères particuliers 你好 صباح الخير <class 'str'> 89


In [12]:
with open('chaine.txt', mode='rb') as f:   #utilise par défaut l'encodage que votre système utilise par défaut, donc cela peut être n'importe quoi allant de l'ASCII à l'ISO-8859-1
    b = f.read()
print(b, type(b), len(b))

b"Ceci est une chaine d'octets\nCeci est une chaine de caract\xc3\xa8res particuliers \xe4\xbd\xa0\xe5\xa5\xbd \xd8\xb5\xd8\xa8\xd8\xa7\xd8\xad \xd8\xa7\xd9\x84\xd8\xae\xd9\x8a\xd8\xb1" <class 'bytes'> 103


In [13]:
txt2 = b.decode('utf8')
print(txt2, type(txt2))

Ceci est une chaine d'octets
Ceci est une chaine de caractères particuliers 你好 صباح الخير <class 'str'>


# FORMATS

Nous allons voir plusieurs formats :
- txt
- numpy
- HDF5
- json

# Sauvegarde et lecture avec numpy : format texte

## loadtxt 

In [18]:
import numpy as np

data = np.loadtxt('./data/Coords.txt') 
print (data)


[[-12.  56.   4.]
 [  6.  50.  12.]
 [  8.  36.   2.]
 [ 24.  24. -18.]
 [-12.  22.  28.]
 [-12.  22.  26.]
 [-32.  20. -18.]
 [-28.  16.  32.]
 [-48.  14.   8.]
 [-10.  10.  44.]
 [-34.   8.  38.]
 [  4.   6.  50.]
 [  4.   6.  50.]
 [ 10.   4.  74.]
 [ -2.   4.  44.]
 [ 24.   4. -10.]
 [ 24.   4. -16.]
 [ 40.   2.  62.]
 [-54.   2.  38.]
 [-26.  -4.  70.]]


## savetxt

In [19]:
data = np.zeros(shape = (1000,1000), dtype = "float32")
print(data)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
np.savetxt("./data/data.txt", data, fmt = "%f")

# Sauvegarde et lecture avec numpy : format .npy, load et save

Plus rapide et plus léger. Numpy = compact en mémoire, format binaire compacte.

In [21]:
np.save("./data/data.npy", data)

In [22]:
data2 = np.load("./data/data.npy")
data2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(1000, 1000), dtype=float32)

# Sauvegarde et lecture avec JSON

Format de données texte
avantage : lisible (pour les humains)
mais gros fichiers et plutôt lent

In [20]:
import json

# Un dictionnaire avec des données variées
donnees = {
    "nom_experience": "EEG repos",
    "date": "2026-03-12",
    "canaux": ["Fp1", "Fp2", "C3", "C4", "O1", "O2"],
    "parametres": {
        "frequence_echantillonnage": 250,  # Hz
        "duree": 60,  # secondes
    },
    "signaux": [
        [0.1, 0.2, 0.3],  # Exemple de données EEG (simplifié)
        [0.4, 0.5, 0.6]
    ],
    "notes": "Premier enregistrement avec le nouveau matériel."
}

# Sauvegarder dans un fichier JSON
with open('./data/experience_eeg.json', 'w', encoding='utf-8') as f:
    json.dump(donnees, f, indent=4)  # `indent=4` pour une meilleure lisibilité

In [24]:
# lire un fichier json
with open('./data/experience_eeg.json', 'r', encoding='utf-8') as f:
    donnees_chargees = json.load(f)

# Afficher les données
print("Nom de l'expérience :", donnees_chargees['nom_experience'])
print("Canaux :", donnees_chargees['canaux'])
print("Signaux :", donnees_chargees['signaux'])

Nom de l'expérience : EEG repos
Canaux : ['Fp1', 'Fp2', 'C3', 'C4', 'O1', 'O2']
Signaux : [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]


# Sauvegarde et lecture avec HDF5
Format de données binaire, optimisé (plus volumineux que le binaire : binaire compact hiérarchique)\
Compact, compression possible, rapide

In [25]:
import h5py

In [26]:
# Sauvegarder dans un fichier HDF5
with h5py.File('./data/data.h5', 'w') as f:
    f.create_dataset('data', data=data) #, compression="gzip")  # Option de compression

In [28]:
# Interressant surtout pour données complexes (données + méta données)
# ex : EEG simulé
eeg = np.random.rand(1000, 8)  # 1000 échantillons, 8 canaux
fs = 250  # Fréquence d'échantillonnage (Hz)
canaux = ['Fp1', 'Fp2', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2']

# Sauvegarder dans un fichier HDF5
with h5py.File('./data/eeg.h5', 'w') as f:
    f.create_dataset('eeg', data=eeg, compression="lzf")  # Option de compression
    f.attrs['fs'] = fs

    # Sauvegarder les noms des canaux (nécessite un type spécial pour les chaînes de caractères)
    dt = h5py.special_dtype(vlen=str)
    f.create_dataset('canaux', data=canaux, dtype=dt)

In [29]:
# Charger les données depuis le fichier HDF5
with h5py.File('./data/eeg.h5', 'r') as f:
    eeg_charge = f['eeg'][:]
    fs = f.attrs['fs']
    canaux = [s.decode('utf-8') for s in f['canaux'][:]]

    print("Forme des données EEG :", eeg_charge.shape)
    print("Fréquence d'échantillonnage :", fs, "Hz")
    print("Canaux :", canaux)

Forme des données EEG : (1000, 8)
Fréquence d'échantillonnage : 250 Hz
Canaux : ['Fp1', 'Fp2', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2']


# Concept d'ARBORESCENCE

![Schema](./img/mac_tree.png)     ![Schema](./img/win_tree.jpg)    ![Schema](./img/linux-tree.png) 

## Racine :

    mac et linux : /
    
    windows : C:\

##  Arborescences de fichiers : Linux, macOS et Windows

###  Organisation commune

Tous les systèmes d'exploitation utilisent une **structure hiérarchique** pour organiser les fichiers :
- Les fichiers sont dans des dossiers (répertoires), qui peuvent contenir d'autres fichiers ou dossiers.
- On distingue les **chemins absolus** (depuis la racine) et **relatifs** (depuis le dossier courant).

---

### Linux / macOS (Unix-like)

- L’arborescence commence par la **racine `/`**
- Dossiers principaux :
  - `/home/nom_utilisateur` : dossier personnel
  - `/etc`, `/usr`, `/tmp` : configuration, programmes, fichiers temporaires
- Le **séparateur de chemins** est `/`

Exemple : `/home/alice/Documents/projet.txt`

---

###  Windows

- Organisation basée sur des **lettres de lecteur** : `C:\`, `D:\`, etc.
- Le **séparateur de chemins** est `\` (antislash)
- Dossier utilisateur : `C:\Users\NomUtilisateur`

Exemple : `C:\Users\Alice\Documents\projet.txt`

---

###  Portabilité

Sous Python, le module `pathlib` permet de manipuler les chemins de façon **portable**, c'est-à-dire quel que soit le système (Windows, macOS ou Linux).


### Chemin absolu :
    
    linux : /home/alex/projets/formation_python/
    
    windows : C:\\Users\\alex\\projets\\formation_python\\   (double\ car caractère d'échapement)
    
    mac : /Disque_dur/Users/alex/projets/formation_python/

---


### Chemin relatif :

    ./          là ou je suis actuellement
    ../       je remonte d'un dossier par rapport à là ou je suis
    
    idem windows mais avec \
    
    
    exemple : np.loadtxt('./data/Coords.txt') 

---



- Windows utilise \ par héritage de MS-DOS (années 80), tandis qu'Unix/Linux/macOS utilisent / depuis les années 70.

- Compatibilité moderne :
Windows accepte souvent / aussi, mais Linux/macOS rejettent \ (caractère d'échappement : n -> \n retour à la ligne).

- Bonne pratique :
Préférez / pour un code multi-OS (ex: Path("dossier/fichier") en Python).

---
    
    

## Le module os (Operating System)



### 1 - Prendre de l'information sur le sysème de fichiers

+ import os


+ os.uname() : infos système


+ os.getcwd() : pour obtenir le répertoire en cours


+ os.path.abspath(path) : retourne une version absolue du chemin path


+ os.path.relpath(path[, start]) : retourne une version relative du chemin path. Par défaut, par rapport au working dir, sinon : spécifier un argument start qui sera le répertoire de base


### 2 - Faire des actions sur le système de fichiers

+ os.chdir(foldername)  : va dans le répertoire spécifié


+ os.mkdir(’mydir’) : crée le répertoire mydir


+ os.rename(oldname, newname) : renomme oldname en newname


+ os.remove(filename) : efface le fichier filename


### 3 - Utilitaires

+ os.path.join(morceau1, morceau2) : colle deux morceaux de chemin ensemble  en utilisant les caractères adaptés au système


+ os.path.expanduser("~") : retourne le chemin vers le répertoire "Home" de l'utilisateur sur la machine


+ os.path.split(racine/nomfichier_ou_rep) : permet de séparer la dernière branche de la racine, résultat sous forme de tuple
    *ex : (filepath, filename) = os.path.split("/Users/admin/Desktop") 
    *filename: "Desktop"


+ os.path.splitext(nomfichier.extension) : sépare le nom de l'extension. Résultat sous forme de tuple


+ os.listdir(path) :  prend un nom de chemin et retourne une liste du contenu du répertoire.


+ os.path.isfile : pour séparer les fichiers des répertoires. (os.path.isdir existe aussi). isfile prend un nom de chemin et :
     *retourne 1 / True si le chemin représente un fichier
     *0 / False dans le cas contraire. 


+ os.walk(top, topdown=True) : à parir de top (repertoire racine), parcourt l'arborescence en descendant si topdown=True, en montant sinon, et renvoie un tuple : (dirpath, dirnames, filenames) qui contient tous les répertoires dirnames rencontrés avec les fichiers filenames qui s'y trouvent

In [1]:
import os

for dossier, sous_dossiers, fichiers in os.walk('./img/'):
    for fichier in fichiers:
        print(os.path.join(dossier, fichier))

./img/np_concat_2.png
./img/mac_tree.png
./img/np_concat_0.png
./img/np_exo_argmin.png
./img/dataset-diagram-logo.png
./img/linux-tree.png
./img/BIDS_example.png
./img/groupby.png
./img/neo_multi_segment_diagram.png
./img/win_tree.jpg
./img/axis.png
./img/np_3D.png
./img/neo_base_schematic.png
./img/np_concat_1.png


In [2]:
os.listdir('./')

['ma_bibliotheque.py',
 'EEG_MNE_exo.ipynb',
 'toto.txt',
 'sklearn.ipynb',
 'img',
 'plotly.ipynb',
 'numpy.ipynb',
 'toto2.txt',
 'xarray.ipynb',
 '.ipynb_checkpoints',
 'base_language_python.ipynb',
 'data',
 'file_manipulation.ipynb',
 'EEG_MNE.ipynb',
 'ephyviewer.ipynb',
 'chaine.txt',
 'formula_statsmodels.ipynb',
 'pandas_exo.ipynb',
 'skimage.ipynb',
 'ephyviewer_example.py',
 'physio_example.ipynb',
 'scipy_overview.ipynb',
 'networkx.ipynb',
 'pandas_base.ipynb',
 'matplotlib_base.ipynb',
 'polars.ipynb',
 'python-neo.ipynb',
 'panel_DataExploration_WebAppFramework.ipynb',
 'numba_example.ipynb',
 'torch.ipynb']

## Le module pathlib = nouvelle méthode

In [1]:
from pathlib import Path

home = Path.home()
home

PosixPath('/home/tkz')

In [4]:
ici = Path('.').absolute()
ici

PosixPath('/home/tkz/Documents/formations/Formation_python_2026/Formation_2026_Python_data_analyse/notebooks')

In [5]:
doc = home / 'Documents'
doc

PosixPath('/home/tkz/Documents')

In [6]:
for item in Path('/').iterdir():
    print(item)

/sbin
/lib
/home
/libx32
/lib.usr-is-merged
/boot
/bin
/swapfile
/run
/dev
/lib64
/sys
/cdrom
/snap
/lib32
/media
/tmp
/proc
/root
/usr
/etc
/.local
/srv
/lost+found
/debug
/mnt
/sbin.usr-is-merged
/opt
/var
/bin.usr-is-merged


In [7]:
file_path = Path('./img/linux-tree.png')

print(file_path.is_file())

print(file_path.stem)            # nom du fichier sans l'extension
print(file_path.suffix)
print(file_path.parent)
print(file_path.parents[0])
print(file_path.parents[1])
#print(file_path.parents[2])



True
linux-tree
.png
img
img
.


In [5]:
ici = Path('.').absolute()

for file in ici.glob('*.ipynb'):
    print(file)

/home/tkz/Documents/formations/Formation_python_2026/Formation_2026_Python_data_analyse/notebooks/EEG_MNE_exo.ipynb
/home/tkz/Documents/formations/Formation_python_2026/Formation_2026_Python_data_analyse/notebooks/sklearn.ipynb
/home/tkz/Documents/formations/Formation_python_2026/Formation_2026_Python_data_analyse/notebooks/plotly.ipynb
/home/tkz/Documents/formations/Formation_python_2026/Formation_2026_Python_data_analyse/notebooks/numpy.ipynb
/home/tkz/Documents/formations/Formation_python_2026/Formation_2026_Python_data_analyse/notebooks/xarray.ipynb
/home/tkz/Documents/formations/Formation_python_2026/Formation_2026_Python_data_analyse/notebooks/base_language_python.ipynb
/home/tkz/Documents/formations/Formation_python_2026/Formation_2026_Python_data_analyse/notebooks/file_manipulation.ipynb
/home/tkz/Documents/formations/Formation_python_2026/Formation_2026_Python_data_analyse/notebooks/EEG_MNE.ipynb
/home/tkz/Documents/formations/Formation_python_2026/Formation_2026_Python_data_a

In [9]:
# recursif
for file in Path('/home/tkz/').glob('**/*.ipynb'):
    print(file)

#for file in Path('/home/tkz/').rglob('*.ipynb'):
#    print(file)


/home/tkz/.config/Code/User/History/14e247b0/pm7e.ipynb
/home/tkz/.config/Code/User/History/14e247b0/Vvoa.ipynb
/home/tkz/.config/Code/User/History/14e247b0/rYg1.ipynb
/home/tkz/.config/Code/User/History/14e247b0/4Wvr.ipynb
/home/tkz/.config/Code/User/History/14e247b0/crRL.ipynb
/home/tkz/.config/Code/User/History/14e247b0/Lt9r.ipynb
/home/tkz/.config/Code/User/History/43a77f0a/iGMr.ipynb
/home/tkz/.config/Code/User/History/-71418e38/HmuT.ipynb
/home/tkz/.config/Code/User/History/-71418e38/caOD.ipynb
/home/tkz/.config/Code/User/History/-71418e38/ggc2.ipynb
/home/tkz/.config/Code/User/History/-71418e38/yEcQ.ipynb
/home/tkz/.config/Code/User/History/-71418e38/ldVG.ipynb
/home/tkz/.config/Code/User/History/-40e1ea2a/aoXv.ipynb
/home/tkz/.config/Code/User/History/-442b13d6/gXTc.ipynb
/home/tkz/.config/Code/User/History/-329ff391/gsKx.ipynb
/home/tkz/.config/Code/User/History/-329ff391/Gx8j.ipynb
/home/tkz/.config/Code/User/History/-329ff391/7uvf.ipynb
/home/tkz/.config/Code/User/History/-3

## EXPLORATION DE FICHIERS

Exploreration du dossier 'data/data_folder' :


In [4]:
path_data = './data/data_folder/'

# recursif
#for file in Path(path_data).glob('**/*'):
#    print(file)

for file in Path(path_data).rglob('*'):
    print(file)


data/data_folder/ST01
data/data_folder/HJ02
data/data_folder/LM04
data/data_folder/UJ03
data/data_folder/ST01/session_3.npy
data/data_folder/ST01/session_1.npy
data/data_folder/ST01/session_4.npy
data/data_folder/ST01/session_5.npy
data/data_folder/ST01/session_2.npy
data/data_folder/HJ02/session_3.npy
data/data_folder/HJ02/session_1.npy
data/data_folder/HJ02/session_4.npy
data/data_folder/HJ02/session_5.npy
data/data_folder/HJ02/session_2.npy
data/data_folder/LM04/session_3.npy
data/data_folder/LM04/session_1.npy
data/data_folder/LM04/session_4.npy
data/data_folder/LM04/session_5.npy
data/data_folder/LM04/session_2.npy
data/data_folder/UJ03/session_3.npy
data/data_folder/UJ03/session_1.npy
data/data_folder/UJ03/session_4.npy
data/data_folder/UJ03/session_5.npy
data/data_folder/UJ03/session_2.npy


Vérifions que les fichiers numpy sont consistants

In [5]:
import numpy as np
root_path = Path(path_data)

# Parcours des sous-dossiers
for subdir in root_path.iterdir():
    if subdir.is_dir():
        print(subdir)
        
        # Parcours des fichiers .npy dans le sous-dossier
        for npy_file in subdir.glob("*.npy"):
            
            key_name = f"{subdir.name}/{npy_file.name}"
            current_npy = np.load(npy_file)
            print(current_npy.shape)
            #print('valeur 1 : ', current_npy[0][0])  

data/data_folder/ST01
(4, 3)
(4, 3)
(4, 3)
(4, 3)
(4, 3)
data/data_folder/HJ02
(4, 3)
(4, 3)
(4, 3)
(4, 3)
(4, 3)
data/data_folder/LM04
(4, 3)
(4, 3)
(4, 3)
(4, 3)
(4, 3)
data/data_folder/UJ03
(4, 3)
(4, 3)
(4, 3)
(4, 3)
(4, 3)


# EXERCICE

Vous souhaitez reproduire les résultats d'une étude, dont les données ont été partagées sur OpenNeuro (excellent !) \
'Poetry Assessment EEG Dataset 2' : https://openneuro.org/datasets/ds006647/versions/1.0.1 \
Il s'agit d'un set de données EEG sous format BIDS

BIDS kesako ? \
https://en.wikipedia.org/wiki/Brain_Imaging_Data_Structure \
https://bids.neuroimaging.io/tools/index.html

![schema](./img/BIDS_example.png)


Les données sont dans votre répertoire 'data/BIDS_example' \
1 - Explorer ces données : qu'y a t'il comme type de fichiers ? \
2 - Afficher les durées d'enregistrement de chaque EEG ('RecordingDuration')

# SOLUTION

In [9]:
path_data = './data/BIDS_example/'
root_path = Path(path_data)

#1
with open(path_data + 'dataset_description.json') as f:
        dataset_desc = json.load(f)   
# Afficher les données
print("Nom de l'expérience :", dataset_desc['Name'])
print('\n')


#for file in Path(path_data).rglob('*'):
#    print(file)

Nom de l'expérience : Poetry Assessment EEG Dataset 2




In [10]:
#2
for file in Path(path_data).rglob('*/*task-readpoetry_eeg.json*'):
    #print(file)

    #print(type(file))
    sujet = str(file).split('/')[2]
    print('sujet : ', sujet)
    
    with open(file) as f:
        info_task = json.load(f)
        #print(info_task)
        print("Durée de l'enregistrement : " + str(info_task['RecordingDuration']))


sujet :  sub-002
Durée de l'enregistrement : 8731
sujet :  sub-001
Durée de l'enregistrement : 8207
sujet :  sub-003
Durée de l'enregistrement : 6745
sujet :  sub-004
Durée de l'enregistrement : 7569
