
# Numpy


Rappel :

Python fournit des objets de haut niveau (ex : int, float) et des conteneurs : list (sans coût pour l'ajout et l'insertion), dictionnaires (recherche facile)
Python n'a pas été conçu à la base pour le calcul scientifique, mais depuis 2003 énormément d'outils ont été développés pour.

Numpy est une librairie d'extention à Python pour les tableaux multidimentionnels.
- calcul vectoriel avec représentation multidimentionnelle (ex : vecteur 1D, serie temporelle 2D, IRMAnat 3D, IRM Fonctionnelle 4D)
- efficace en gestion mémoire (proche hardware - gd ensemble de nbres ordonnés)
- conçu pour le calcul scientifique
- "brique" de base pour tout l'ecosystème scientifique (pandas/mne/scipy/...)

In [1]:
import numpy as np             # convention d'import
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

Opérations numériques rapides :

In [2]:
L = list(range(1000))             # Liste
%timeit [i**2 for i in L]

a = np.arange(1000)         # Numpy array
%timeit a**2

#pouquoi ? numpy est écrit en C !

41.2 μs ± 2.02 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
707 ns ± 22.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Multi-dimensions : ndim, shape, size

## 1D

In [4]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [5]:
a.ndim

1

In [6]:
a.shape # 'taille' des dimensions

(4,)

In [7]:
a.size # nbre d'elements total

4

## 2D, 3D, ... ND

In [8]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
print('b : ', b)
print('b.ndim : ', b.ndim)
print('b.shape : ', b.shape)
print('b.size : ', b.size)

# attention à la necessité de dimentions cohérentes 
# b = np.array([[0, 1, 2], [3, 4, 5, 6]]) va pas marcher

b :  [[0 1 2]
 [3 4 5]]
b.ndim :  2
b.shape :  (2, 3)
b.size :  6


In [9]:
c = np.array([
        [[1,2,3], [2,3,4], [3,4,5], [4,5,6]],
        [[2,3,4], [3,4,5], [4,5,6], [5,6,7]],
        [[3,4,5], [4,5,6], [5,6,7], [6,7,8]],
        [[4,5,6], [5,6,7], [6,7,8], [7,8,9]],
        [[5,6,7], [6,7,8], [7,8,9], [8,9,10]]
    ])
print('c.ndim : ', c.ndim)
print('c.shape : ', c.shape)
print('c.size : ', c.size)

c.ndim :  3
c.shape :  (5, 4, 3)
c.size :  60


![Image](img/np_3D.png)

# Fonctions

En pratique, on entre rarement les nombres à la main...

### Eléments réguliairement espacés :

In [12]:
a = np.arange(10) # 0 .. n-1  (!)
a
#np.arange?
#equivalent du range mais en numpy array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b = np.arange(1, 9, 2) # début, fin (exclusive), pas
b

array([1, 3, 5, 7])

In [14]:
c = np.arange(-5.2, 2.2, 0.8)
c

array([-5.2, -4.4, -3.6, -2.8, -2. , -1.2, -0.4,  0.4,  1.2,  2. ])

### Ou espacés en donnant le nombre de points :

In [15]:
c = np.linspace(0, 1, 6)   # début, fin, nombre de points
c
#np.linspace?
# attention, ici c'est inclus !

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [16]:
d = np.linspace(0, 1, 5, endpoint=False)
d

#(intro mot clef)

array([0. , 0.2, 0.4, 0.6, 0.8])

### Tableaux usuels :

In [17]:
a = np.ones((3, 3))  # np.ones((3, 3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
b = np.zeros((2, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Generateur de nombres aléatoires

In [20]:
rng = np.random.default_rng(seed=None)
#rng = np.random.default_rng(seed=2205)

a = rng.normal(size=(10, 2))
a

array([[ 0.36558368, -1.62447742],
       [-0.80248379, -1.19911164],
       [ 0.93456188, -1.98180846],
       [-0.60788242,  0.62384128],
       [ 0.38008357, -0.18774977],
       [ 1.96424846, -0.58270914],
       [-1.38278496, -0.48995816],
       [ 0.76556846, -1.1786015 ],
       [ 0.40097651, -0.70574976],
       [ 2.09091759, -0.89625049]])

In [21]:
a = rng.uniform(size=5)
a

array([0.75197724, 0.01755693, 0.98864071, 0.76515486, 0.47514363])

In [25]:
a = rng.integers(size=15, low=5, high=20)
a

array([16, 11, 17,  6, 11,  9,  9, 16,  7, 13,  6, 10, 19, 12,  5])

# dtype

In [26]:
a = np.array([0, 1, 2, 3])
print(a)
a.dtype

[0 1 2 3]


dtype('int64')

In [27]:
b = np.array([0., 1., 2., 3.])
print(b)
b.dtype


[0. 1. 2. 3.]


dtype('float64')

In [28]:
import numpy as np
d = np.array([1.33,2,3.,4])
print(d)
d.dtype

# en numpy, les tableaux sont forcément homogènes car ils sont continus et compactes en mémoire.
# lors de mix numpy prends le dtype le plus utile 

[1.33 2.   3.   4.  ]


dtype('float64')

### Vous devez expliciter le dtype à la création

In [29]:
c1 = np.arange(10, dtype='float64')
print(c1)
c1.dtype
#import sys
#sys.getsizeof(c1) # taille en mémoire en byte (octet)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


dtype('float64')

In [30]:
c2 = np.arange(10, dtype='int16')
print(c2)
c2.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int16')


### Le type par défaut est généralement "float64" 

In [32]:
a = np.ones((3, 3))
print(a)
print(a.dtype)

b = np.ones((3, 3), dtype = "int32")
print(b)
print(b.dtype)

# d'ou, la bonne pratique est de spécifier le dtype à chaque fois

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64
[[1 1 1]
 [1 1 1]
 [1 1 1]]
int32


### Autres types :

In [33]:
# Complexe :
a = np.array([1+2j, 3+4j, 5+6*1j])
a.dtype

dtype('complex128')

In [34]:
# Booléen
b = np.array([True, False, False, True])
b.dtype

dtype('bool')

In [35]:
# String
c = np.array(['Bonjour', 'Hello', 'Hallo',])
c.dtype             # <--- strings contenant max. 7 lettres

# U7 : unique 7 caractere

dtype('<U7')

# Introduction aux opérations

In [36]:
c = np.arange(10, dtype='float64')
d = np.arange(10, dtype='float64')

print('c : ', c)
print('d : ', d)

c :  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
d :  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [37]:
c+1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
c

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
c+d

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [40]:
c*10+d

array([ 0., 11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [41]:
res = np.log10(c)
print(res)

[      -inf 0.         0.30103    0.47712125 0.60205999 0.69897
 0.77815125 0.84509804 0.90308999 0.95424251]


/tmp/ipykernel_15534/2825777501.py:1: RuntimeWarning: divide by zero encountered in log10
  res = np.log10(c)


In [42]:
flags = np.isinf(res)
flags

array([ True, False, False, False, False, False, False, False, False,
       False])

In [43]:
np.inf

inf

In [44]:
-np.inf

-inf

In [45]:
np.nan #Not A Number

nan

In [46]:
np.nan + 5

nan

In [47]:
a = np.arange(9)
print(a)
flags = (a>5)
flags

[0 1 2 3 4 5 6 7 8]


array([False, False, False, False, False, False,  True,  True,  True])

In [48]:
a = np.arange(9)
print(a)
flags = (a>2) & (a<=6)
flags



[0 1 2 3 4 5 6 7 8]


array([False, False, False,  True,  True,  True,  True, False, False])

In [49]:
a = np.arange(9)
print(a)
flags = (a>2) | (a<=6)
flags


[0 1 2 3 4 5 6 7 8]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [50]:
flags2 = ~flags
flags2

array([False, False, False, False, False, False, False, False, False])

### reshape

In [51]:
a = np.arange(24) 
print(a)
print(a.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [52]:

a2 = a.reshape(6,4) 
print(a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [53]:
a3 = a.reshape(4,2,3)
print(a3.shape)
print(a3)

(4, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [54]:
a3 = a.reshape(4,-1,3)
print(a3.shape) ### la dimension par default vaut ici (24/4)/3 = 2



(4, 2, 3)


### Lecture/écriture d'un seul élément

Pour un tableau à deux dimensions comme celui-ci :

In [55]:
a = np.arange(12).reshape(4,3)
print (a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [56]:
e = a[1,1]
print(e)

4


In [57]:
a[1,2] = 1000
a

array([[   0,    1,    2],
       [   3,    4, 1000],
       [   6,    7,    8],
       [   9,   10,   11]])

### Slice

In [59]:
a = np.arange(6).reshape(1,6)  + 10*np.arange(6).reshape(6, 1)
print(a)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [60]:
a2 = a[3:, 0:5:2]   # array[start:stop:step]   avec stop exclu
a2

array([[30, 32, 34],
       [40, 42, 44],
       [50, 52, 54]])

### Par masque booléen

Par exemple, si on a un signal aléatoire dont on ne veut garder que les valeurs positives

In [63]:
rng = np.random.default_rng(seed=2205)
a = rng.normal(size=12)
a

array([-1.39349566, -1.80292396, -0.97854262,  1.36885844,  0.2158217 ,
       -0.22337887,  0.95713794,  0.98730008, -0.48365   ,  0.37125701,
        0.67147601, -0.65440892])

In [64]:
keep = (a>0.)
print(keep)
not_keep = ~keep # not en boolean (existe aussi np.logical_not)
print(not_keep)

[False False False  True  True False  True  True False  True  True False]
[ True  True  True False False  True False False  True False False  True]


In [65]:
print(a[keep])

[1.36885844 0.2158217  0.95713794 0.98730008 0.37125701 0.67147601]


### Selection explicite d'une liste

In [66]:
a = np.arange(7)*10
a

array([ 0, 10, 20, 30, 40, 50, 60])

In [67]:
l = [2, 4, 0]
a2 = a[l]
a2

array([20, 40,  0])

### View and copy

Un tableau issu d'un même tableau est une *'view'*.


In [71]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a2 = a[2:-2]
print(a2)
a2[0:6] = np.arange(6)*-10
print(a2)
print(a)

[  0 -10 -20 -30 -40 -50]
[  0 -10 -20 -30 -40 -50]
[  0   1   0 -10 -20 -30 -40 -50   8   9]


Sinon il faut faire une copie explicite.

In [76]:
a = np.arange(10)
a2 = a[2:-2].copy()
a2[0:6] = np.arange(6)*-10
print(a2)
print(a)

[  0 -10 -20 -30 -40 -50]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# nan = not a number

### nan et inf

In [77]:
a = np.arange(5, dtype='float64')
a[2] = np.nan
a

array([ 0.,  1., nan,  3.,  4.])

In [82]:
print('infini :', np.inf)
print('moins l\'infini :', -np.inf)
# on peut comparer des valeurs standard à np.inf
print('comparaison 0 < inf :', 0 < np.inf)
print('comparaison 0 > inf :', 0 > np.inf)



infini : inf
moins l'infini : -inf
comparaison 0 < inf : True
comparaison 0 > inf : False


In [79]:
print('overflow :', np.exp(1e42))

overflow : inf


/tmp/ipykernel_15534/2963031205.py:1: RuntimeWarning: overflow encountered in exp
  print('overflow :', np.exp(1e42))


In [81]:
# attention en cas d'overflow les comparaisons sont fausses
print('comparaison avec overflow :', np.exp(1e42) == np.exp(1e40))

comparaison avec overflow : True


/tmp/ipykernel_15534/1439738699.py:2: RuntimeWarning: overflow encountered in exp
  print('comparaison avec overflow :', np.exp(1e42) == np.exp(1e40))


In [83]:
a = np.array([-1,0,1])/0.0
print(a)

[-inf  nan  inf]


/tmp/ipykernel_15534/492010968.py:1: RuntimeWarning: divide by zero encountered in divide
  a = np.array([-1,0,1])/0.0
/tmp/ipykernel_15534/492010968.py:1: RuntimeWarning: invalid value encountered in divide
  a = np.array([-1,0,1])/0.0


In [85]:
print(np.isnan(a))
print(np.isinf(a))

[False  True False]
[ True False  True]


### Concatenation de tableau

In [87]:
a = np.arange(3)
b = np.arange(5)

c = np.concatenate((a,b)) ### concatene par défault selon la premiere dimension

print(c)

[0 1 2 0 1 2 3 4]


In [89]:
### en multi dimension, on precise axis

a = np.ones((3,4,5))
b = np.ones((3,4,5))

c = np.concatenate((a,b),axis = 0) ### concatene selon la premiere dimension

print(c.shape)

(6, 4, 5)


![Image](img/np_concat_0.png)

In [90]:
### Si les dimensions (autre que celle ou l'on concatène) ne correspondent pas : ça ne marche pas !

a = np.ones((3,4,5))
b = np.ones((3,5,3))

c = np.concatenate((a,b),axis = 1) 

print(c.shape)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 5 and the array at index 1 has size 3

![Image](img/np_concat_2.png)

### stack et newaxis

np.stack permet d'empiler des tabelaux avec ajout de dimmension.

newaxis permet d'ajouter une dimension à un tableau existant. 

Par exemple, un vecteur n'a qu'une seule dimension:

In [93]:
a = np.array(np.arange(10),dtype = 'int64')

print(a)
print(a.shape)

b = np.array(np.arange(10,20),dtype = 'int64')
print(b)
print(b.shape)

np.concatenate((a,b),axis = 0)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[10 11 12 13 14 15 16 17 18 19]
(10,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [94]:
np.concatenate((a,b),axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [95]:
np.concatenate((a[:, np.newaxis],b[:, np.newaxis]),axis = 1)

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [97]:
np.stack((a,b),axis=1)

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

# Operations de réduction: mean/std, max,  sum etc.

Avec le meme principe de 'axis', il est tres facile de reduire un tableau:

![Image](img/axis.png)

In [113]:
rnd = np.random.default_rng(seed=2406)
m = rnd.integers(size=(3, 5), low=0, high=10)


print(m)

##Petit truc pour connaitre l'axis: c'est la dimension qui disparait

print()
mean_m = np.mean(m,axis = 0) 
print(mean_m) ### ici la dimension colonne (2) disparait (on ne garde que les lignes)
print()
mean_m = np.mean(m,axis = 1)
print(mean_m)
print()
mean_c = np.mean(m,axis = None)
print(mean_c)

[[3 5 6 4 1]
 [9 2 2 3 9]
 [7 5 3 9 7]]

[6.33333333 4.         3.66666667 5.33333333 5.66666667]

[3.8 5.  6.2]

5.0


### ça marche avec plein d'opérateur

In [ ]:
### std
std_c_1 = np.std(m,axis = 1)

print(std_c_1)

[1.72046505 3.28633535 2.03960781]


In [ ]:
### max
max_c_0 = np.max(m,axis = 0)

print(max_c_0)

[9 5 6 9 9]


In [ ]:
### min
min_c_0 = np.min(m,axis = 0)

print(min_c_0)

In [117]:
### argmax
argmax_c_0 = np.argmax(m,axis = 0)

print(argmax_c_0)

[1 0 0 2 1]


### alegbre lineaire

In [119]:
a = np.ones(shape = (4,4))*3
b = np.ones(shape = (4,4))*2
print(a)
print(b)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [120]:
### produit de chaque element

c = a*b 
print(c)

[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [124]:
# produit matricielle

c = np.dot(a,b)
print(c)


[[24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]]


In [126]:
c = a @ b
print(c)

[[24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]]


In [127]:
## idem pour inverse

mat = rng.integers(low=1, high=6, size=(4,4)).astype("float64")

print(mat)

[[1. 1. 5. 1.]
 [4. 1. 3. 3.]
 [3. 1. 5. 4.]
 [1. 5. 4. 3.]]


In [129]:
# division par element
c = 1 / mat
print(c)

[[1.         1.         0.2        1.        ]
 [0.25       1.         0.33333333 0.33333333]
 [0.33333333 1.         0.2        0.25      ]
 [1.         0.2        0.25       0.33333333]]


In [130]:
## on obtient la matrice inverse
inv_mat = np.linalg.inv(mat)

print(inv_mat)

[[ 0.10743802  0.52066116 -0.38016529 -0.04958678]
 [ 0.01652893  0.15702479 -0.2892562   0.2231405 ]
 [ 0.25619835 -0.0661157   0.01652893 -0.04132231]
 [-0.40495868 -0.34710744  0.58677686  0.03305785]]


In [133]:
np.round((inv_mat @ mat))

array([[ 1.,  0.,  0., -0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1., -0.],
       [ 0.,  0.,  0.,  1.]])